### ISSUE TITLE
why `batch` is not appropriate in survival analysis?

### ISSUE THREAD

**Issue by bnuzyc91** [liupei101/TFDeepSurv#10]
@liupei101  in the dsl.py you have added this comment "Since style of `batch` is not appropriate in survival analysis."

Could you please advise why batch (mini-batch) training is not appropriate in survival analysis? I notice that the DeepSur (https://github.com/jaredleekatzman/DeepSurv ) also does not support the mini-batch training.

Based on my understanding, mini-batch should be suitable for any ML problem as long as we train enough epoch. Feel free to correct me if I misunderstand this.

Thank you so much!

**Comment by liupei101** [comment]
To put it straightforwardly, if we dive into the loss function (partial likelihood function), survival analysis is a variant of ranking task.

Since we did not find any reference paper to support running batch training in survival analysis, the code remained as you saw.

Thx for your feedbacks! `TFDeepSurv` has implemented the pipeline in survival analysis, but we can easily find the shorts. We need to add functionality that supports:
- GPU training
- mini-batch training (experimentally)
to speed up the training phase!

In the near future, above plans will not be implemented. Sorry about it!

PRs are welcomed!

**Comment by bnuzyc91** [comment]
Thank you so much for the explanation.  Now I agree that mini-batch may not be a good idea for the survival analysis especially in the case of a rare event (the chance of developing the outcome is low).
