### ISSUE TITLE
What are the complete names of these algorithms ("wwe", "kp", "bsl", "Breslow" , "Efron" )?

### ISSUE THREAD

**Issue by wangxiaodong1021** [liupei101/TFDeepSurv#4]
What are the complete names of these algorithms ("wwe", "kp", "bsl", "Breslow" , "Efron" )?

**Comment by liupei101** [comment]
Hi, wangxiaodong1021! Thank u for the observation.

There indeed is something unclear in `README`. But it's suggested that u could read or search some knowledge of survival analysis.

- Survival data with ties
For survival data, if there are individuals who all occur the event at the same time, then the survival data is called `With Ties`. In the general case, `Breslow` estimation is applied to model survival data that is with ties. If there are more ties in data, `Efron` estimation will be a better choice. Don't worry, [This](http://soep.ue.poznan.pl/jdownloads/Wszystkie%20numery/Rok%202014/06_borucka.pdf) may help u a lot!

- Estimating the baseline survival function
When predicting the survival function of a patient via `coxph` model, we must get the baseline survival function. Similarly, since the survival data is with ties, the methods with different preciseness are provided for estimating baseline survival function. As shown in comments of code, the algorithm for estimating baseline survival function is as follows:
    (1). `wwe`: WWE (data with ties, more precise)
    (2). `kp`: Kalbfleisch & Prentice Estimator (data without ties)
    (3). `bsl`: breslow (data with ties, but the negative value may exist)
And [This](http://stat.nuk.edu.tw/graduate/96_paper/M0944411.pdf) may be a good introduction about it!

Any problems about this repo/package are welcomed!
